[package]
name = "escape-rs"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "2.12.2", features = ["napi4"] }
napi-derive = "2.12.2"
memchr = "2.5.0"

[build-dependencies]
napi-build = "2.0.1"