/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function escapeHtml(string: string): string
/**
 * Escapes text to prevent scripting attacks.
 *
 * @param text Text value to escape.
 * @return An escaped string.
*/
export declare function escapeTextForBrowser(text: string | number | boolean): string
